-- Training plan workouts table schema for the coaching app
--
-- Stores individual scheduled workouts that make up a training plan
-- (see training_plans_table.sql). Generated by
-- app/api/training_plans/route.ts (POST) and updated by
-- app/api/training_plan_workouts/[id]/route.ts (PATCH) when a user marks
-- a workout complete or adds notes.

CREATE TABLE IF NOT EXISTS public.training_plan_workouts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  training_plan_id uuid NOT NULL REFERENCES public.training_plans(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  scheduled_date date NOT NULL,
  week_number integer NOT NULL,
  workout_type text NOT NULL CHECK (workout_type IN ('Endurance', 'Tempo', 'Threshold', 'VO2', 'Recovery', 'Climbing', 'Long Ride')),
  title text NOT NULL,
  description text,
  duration_minutes numeric,
  distance_miles numeric,
  elevation_feet numeric,
  intensity text,
  completed boolean NOT NULL DEFAULT false,
  completed_at timestamptz,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.training_plan_workouts IS
  'Individual scheduled workouts belonging to a training plan. Rendered in the calendar and weekly views on /training-plans and used by the coaching report generator to summarize weekly plan adherence.';
COMMENT ON COLUMN public.training_plan_workouts.training_plan_id IS 'The plan this workout belongs to.';
COMMENT ON COLUMN public.training_plan_workouts.user_id IS 'References profiles.id / auth.users.id. Denormalized from the parent plan for direct querying by date.';
COMMENT ON COLUMN public.training_plan_workouts.week_number IS '1-indexed week of the plan (7-day blocks starting at the plan''s start_date), used for the weekly view.';
COMMENT ON COLUMN public.training_plan_workouts.workout_type IS 'One of: Endurance, Tempo, Threshold, VO2, Recovery, Climbing, Long Ride.';
COMMENT ON COLUMN public.training_plan_workouts.intensity IS 'Human-readable target intensity/zone description for the workout.';
COMMENT ON COLUMN public.training_plan_workouts.completed IS 'Set by the user from the training plan UI to track adherence.';
COMMENT ON COLUMN public.training_plan_workouts.completed_at IS 'Timestamp when the workout was marked complete.';

CREATE INDEX IF NOT EXISTS training_plan_workouts_plan_id_idx ON public.training_plan_workouts(training_plan_id);
CREATE INDEX IF NOT EXISTS training_plan_workouts_user_date_idx ON public.training_plan_workouts(user_id, scheduled_date);
